# Dev profile - verbose logging + SQL
debug=true
logging.level.org.thymeleaf=DEBUG
logging.level.org.thymeleaf.engine=DEBUG
logging.level.org.springframework.web.servlet=DEBUG
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
